insert into core.pipcsteps(name,filename,filepath,fileorder) values ('1.- Marco Legal','marcolegalPL.php','proteccioncivil/modules/masters/party',1);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('3.- Justificación','justificacionPL.php','proteccioncivil/modules/masters/party',3);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('4.- Objetivos','objetivosPL.php','proteccioncivil/modules/masters/party',4);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('5.- Alcance','alcancePL.php','proteccioncivil/modules/masters/party',5);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.- Subprograma de Prevención','subprogramadeprevencionPL.php','proteccioncivil/modules/masters/party',7);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.1.- Organización','nmorganizacionPL.php','proteccioncivil/modules/masters/party',8);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.2.- Documentación','nmdocumentacionPL.php','proteccioncivil/modules/masters/party',9);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.3.- Analisis de Riesgo','analisisderiesgosPL.php','proteccioncivil/modules/masters/party',10);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.3.1.- Ubicación del Predio','ubicaciondelpredioPL.php','proteccioncivil/modules/masters/party',11);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.4.- Directorio','nmdirectorioPL.php','proteccioncivil/modules/masters/party',12);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.5.- Inventario','nminventarioPL.php','proteccioncivil/modules/masters/party',13);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.6.- Mantenimiento','nmmantenimientoPL.php','proteccioncivil/modules/masters/party',14);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.9.- Capacitación','nmcapacitacionPL.php','proteccioncivil/modules/masters/party',15);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.10.- Programa de Difusión y Concientización','nmprogramadedifusionyconcientizacionPL.php','proteccioncivil/modules/masters/party',16);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('7.11.- Simulacros','nmsimulacrosPL.php','proteccioncivil/modules/masters/party',17);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('8.- Subprograma de Auxilio','subprogramadeauxilioPL.php','proteccioncivil/modules/masters/party',18);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('8.1.- Alertamiento','nmalertamientoPL.php','proteccioncivil/modules/masters/party',19);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('8.2.- Planes de Emergencia','nmplanesdeemergenciaPL.php','proteccioncivil/modules/masters/party',20);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('8.3.- Evaluacion de Daños','nmevaluaciondedanosPL.php','proteccioncivil/modules/masters/party',21);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('9.- Subprograma de Recuperación','subprogramaderecuperacionPL.php','proteccioncivil/modules/masters/party',22);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('9.1..- Vuelta a la Normalidad','nmvueltaalanormalidadPL.php','proteccioncivil/modules/masters/party',23);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('Anexos','anexoPL.php','proteccioncivil/modules/masters/party',24);
insert into core.pipcsteps(name,filename,filepath,fileorder) values ('Inspección en Sitio PIPC','','',25);
